<div id='airquality_widget' class="widget">
  <div class="widget_title">
    <a href="airquality.html">Air Quality</a>
    <a class="widget_control"
      onclick="toggle_widget('airquality')">&diams;</a>
  </div>

  <div class="widget_contents">
  <strong>Outdoor</strong>
  <table>
    <tbody>
      <tr>
        <td class="label">$obs.label.ag_out_atmp</td>
        <td class="data">$current.ag_out_atmp</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_out_rhum</td>
        <td class="data">$current.ag_out_rhum</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_out_rco2</td>
        <td class="data">$current.ag_out_rco2</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_out_pm01</td>
        <td class="data">$current.ag_out_pm01</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_out_pm02</td>
        <td class="data">$current.ag_out_pm02</td>
     </tr>
      <tr>
        <td class="label">$obs.label.ag_out_pm10</td>
        <td class="data">$current.ag_out_pm10</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_out_tvoc</td>
        <td class="data">$current.ag_out_tvoc</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_out_nox</td>
        <td class="data">$current.ag_out_nox</td>
      </tr>
    </tbody>
  </table>

    <strong>Indoor</strong>
  <table>
    <tbody>
          <tr>
        <td class="label">$obs.label.ag_in_atmp</td>
        <td class="data">$current.ag_in_atmp</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_in_rhum</td>
        <td class="data">$current.ag_in_rhum</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_in_rco2</td>
        <td class="data">$current.ag_in_rco2</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_in_pm01</td>
        <td class="data">$current.ag_in_pm01</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_in_pm02</td>
        <td class="data">$current.ag_in_pm02</td>
     </tr>
      <tr>
        <td class="label">$obs.label.ag_in_pm10</td>
        <td class="data">$current.ag_in_pm10</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_in_tvoc</td>
        <td class="data">$current.ag_in_tvoc</td>
      </tr>
      <tr>
        <td class="label">$obs.label.ag_in_nox</td>
        <td class="data">$current.ag_in_nox</td>
      </tr>
    </tbody>
  </table>
  </div>

</div>
